name: geometric
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - cairo=1.18.0
  - certifi=2024.2.2
  - chardet=5.2.0
  - charset-normalizer=2.0.4
  - contourpy=1.2.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - expat=2.5.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.50.0
  - freetype=2.12.1
  - freetype-py=2.3.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - greenlet=3.0.3
  - icu=73.2
  - idna=3.4
  - intel-openmp=2022.1.0
  - jinja2=3.1.3
  - kiwisolver=1.4.5
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-python=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.0.20
  - libcurand=10.3.5.119
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.19
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.80.0
  - libgomp=13.2.0
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.26
  - libpng=1.6.43
  - libsqlite=3.45.2
  - libstdcxx-ng=13.2.0
  - libtasn1=4.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - markupsafe=2.1.3
  - matplotlib-base=3.8.3
  - mkl=2022.1.0
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.0
  - packaging=24.0
  - pandas=2.1.4
  - pcre2=10.43
  - pillow=10.2.0
  - pip=23.3.1
  - pixman=0.43.2
  - pthread-stubs=0.4
  - pycairo=1.26.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.12.2
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytorch=2.2.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - readline=8.2
  - reportlab=4.1.0
  - requests=2.31.0
  - rlpycairo=0.2.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlalchemy=2.0.28
  - sqlite=3.41.2
  - sympy=1.12
  - tk=8.6.13
  - torchaudio=2.2.1
  - torchvision=0.17.1
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - tzdata=2024a
  - urllib3=2.1.0
  - wheel=0.41.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - asttokens==3.0.0
      - attrs==23.2.0
      - cffi==1.17.1
      - click==8.1.7
      - cmake==3.30.2
      - comm==0.2.2
      - debugpy==1.8.13
      - decorator==5.2.1
      - docker-pycreds==0.4.0
      - executing==2.2.0
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - ipykernel==6.29.5
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - matplotlib-inline==0.1.7
      - multidict==6.0.5
      - nest-asyncio==1.6.0
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.2.2
      - prompt-toolkit==3.0.50
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pyg-lib==0.4.0+pt22cu118
      - pygments==2.19.1
      - pyzmq==26.3.0
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - sentry-sdk==2.3.1
      - setproctitle==1.3.3
      - smmap==5.0.1
      - soundfile==0.13.1
      - stack-data==0.6.3
      - threadpoolctl==3.5.0
      - torch-cluster==1.6.3+pt22cu118
      - torch-geometric==2.5.3
      - torch-scatter==2.1.2+pt22cu118
      - torch-sparse==0.6.18+pt22cu118
      - torch-spline-conv==1.2.2+pt22cu118
      - tornado==6.4.2
      - tqdm==4.66.4
      - traitlets==5.14.3
      - wandb==0.17.0
      - wcwidth==0.2.13
      - yarl==1.9.4
